site_name: CaSe Group - Cloud computing and sequencing

# configurations:
## DONT CHANGE

theme:
  name: material
  custom_dir: material
  icon:
    logo: octicons/chevron-right-24

  include_search_page: true
  search_index_only: true

  language: en
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: blue grey
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/replikation
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gcloudchris
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Christian_Brandt5
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/in/christian-b-a2b05018a


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Navigation
## USE SPACE not TAB

nav:
- Team:
        - Christian - phD/head: team/christian.md
        - Mateusz Jundzill - phD student: team/mateusz.md
        - Mike Marquet - phD student: team/mike.md
        - Ricc Spott - phD student: team/ricc.md
        - Mara Lohde - master student: team/mara.md

- Publications: 
        - Peer reviewed: publications/peer.md
        - Preprints: publications/nonpeer.md
- Programs: 
        - Workflows: tools/workflows.md
        - Tools: tools/tools.md
        - Other: tools/other.md
- Tutorials: 
        - shell: tutorials/shell.md
        - python:
              - python general: tutorials/python/python.md
              - jupyter book: tutorials/python/jbook.md
              - pandas: tutorials/python/pandas.md
        - nextflow: tutorials/nextflow.md
        - docker: tutorials/docker.md
